export {default as Home} from './Home/Home'
export {default as Users} from './Users/Users'
export {default as Rooms} from './Rooms/Rooms'
export {default as AddNewRoom} from './AddNewRoom/AddNewRoom'
export {default as Facilities} from './Facilities/Facilities'
export {default as AddNewFacility} from './AddNewFacility/AddNewFacility'
export {default as Ads} from './Ads/Ads'
export {default as AddNewAds} from './AddNewAds/AddNewAds'
export {default as Bookings} from './Bookings/Bookings'
export {default as Login} from './Login/Login'
export {default as Register} from './Register/Register'
export {default as ResetPassword} from './ResetPassword/ResetPassword'
export {default as ChangePassword} from './ChangePassword/ChangePassword'
export {default as ForgetPassword} from './ForgetPassword/ForgetPassword'


